# Generated by Django 5.1.5 on 2025-01-27 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elect_shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='individualentrepreneur',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elect_shop.manufacturer', verbose_name='производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='entrepreneurs',
            field=models.ManyToManyField(blank=True, to='elect_shop.individualentrepreneur', verbose_name='предприниматели'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elect_shop.manufacturer', verbose_name='производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retailnetwork',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elect_shop.manufacturer', verbose_name='производитель'),
        ),
        migrations.AddField(
            model_name='retailnetwork',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retailnetwork',
            name='retail_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elect_shop.retailnetwork', verbose_name='розничная сеть'),
        ),
        migrations.AddField(
            model_name='product',
            name='retailers',
            field=models.ManyToManyField(blank=True, to='elect_shop.retailnetwork', verbose_name='розничные сети'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='retail_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elect_shop.retailnetwork', verbose_name='розничная сеть'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_individual_entrepreneur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_individual_entrepreneur', to='elect_shop.individualentrepreneur', verbose_name='покупатель-индивидуальный предприниматель'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_manufacturer', to='elect_shop.manufacturer', verbose_name='покупатель-производитель'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_retail_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_retail_network', to='elect_shop.retailnetwork', verbose_name='покупатель-розничная сеть'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='elect_shop.product', verbose_name='продукт'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_individual_entrepreneur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_individual_entrepreneur', to='elect_shop.individualentrepreneur', verbose_name='продавец-индивидуальный предприниматель'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_manufacturer', to='elect_shop.manufacturer', verbose_name='продавец-производитель'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_retail_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_retail_network', to='elect_shop.retailnetwork', verbose_name='продавец-розничная сеть'),
        ),
    ]
